// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx4rIvryXkRYxlm7Viz5mymzas58yO9tg',
    appId: '1:553897307650:web:4b722b30ecd41a75e1811b',
    messagingSenderId: '553897307650',
    projectId: 'cmsc23-hamartinez',
    authDomain: 'cmsc23-hamartinez.firebaseapp.com',
    storageBucket: 'cmsc23-hamartinez.appspot.com',
    measurementId: 'G-P73LK6SC9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL3Rvn-n52EWgpN9ihXYtqAuqMxBHg63E',
    appId: '1:553897307650:android:d78ed3e0d2f8695ee1811b',
    messagingSenderId: '553897307650',
    projectId: 'cmsc23-hamartinez',
    storageBucket: 'cmsc23-hamartinez.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIoxXj7ILQWb_qixIkzuDaLdd-IsQuy0c',
    appId: '1:553897307650:ios:541235d05a2cb85de1811b',
    messagingSenderId: '553897307650',
    projectId: 'cmsc23-hamartinez',
    storageBucket: 'cmsc23-hamartinez.appspot.com',
    iosClientId: '553897307650-9asmucf8po8e9r1tcq1mq135umi76grv.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIoxXj7ILQWb_qixIkzuDaLdd-IsQuy0c',
    appId: '1:553897307650:ios:541235d05a2cb85de1811b',
    messagingSenderId: '553897307650',
    projectId: 'cmsc23-hamartinez',
    storageBucket: 'cmsc23-hamartinez.appspot.com',
    iosClientId: '553897307650-9asmucf8po8e9r1tcq1mq135umi76grv.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
